export const HOME = {
    "categorias___":[
       {
          "apresentacao_apresentador":"DESCRIÇÃO/APRESENTAÇÃO DO APRESENTADOR",
          "arquivos_categoria":[
             "Array"
          ],
          "cod_categoria":"495",
          "cod_categoria_pai":"0",
          "cod_cliente":"1258",
          "cor_primaria":"#1c43ff",
          "descricao_categoria":"",
          "flg_mostrar_label":"1",
          "nome_apresentador":"Apresentador",
          "nome_categoria":"Matemática",
          "ordem_categoria":"0",
          "subtitulo_apresentador":"SUB-TÍTULO DO APRESENTADOR",
          "url_foto_apresentador":"2023-07-25_21-23-36_221782_b3804c7c.jpg",
          "url_foto_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-07-26_10-30-10_221782_9593d27c.png",
          "url_foto_full_categoria":"2023-07-25_21-23-36_221782_0f0c5b00.jpg",
          "url_foto_v_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-28-26_221782_80b2a86e.jpg",
          "videos":[
             "Array"
          ]
       },
       {
          "apresentacao_apresentador":"",
          "arquivos_categoria":[
             "Array"
          ],
          "cod_categoria":"496",
          "cod_categoria_pai":"0",
          "cod_cliente":"1258",
          "cor_primaria":"#105693",
          "descricao_categoria":"",
          "flg_mostrar_label":"1",
          "nome_apresentador":"",
          "nome_categoria":"Lingua Portuguesa",
          "ordem_categoria":"5",
          "subtitulo_apresentador":"",
          "url_foto_apresentador":"",
          "url_foto_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-07-26_10-31-55_221782_9cc61ed7.png",
          "url_foto_full_categoria":"",
          "url_foto_v_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-28-42_221782_3a0baa20.jpg",
          "videos":[
             "Array"
          ]
       },
       {
          "apresentacao_apresentador":"",
          "arquivos_categoria":[
             "Array"
          ],
          "cod_categoria":"537",
          "cod_categoria_pai":"0",
          "cod_cliente":"1258",
          "cor_primaria":"#360a84",
          "descricao_categoria":"",
          "flg_mostrar_label":"1",
          "nome_apresentador":"",
          "nome_categoria":"História",
          "ordem_categoria":"10",
          "subtitulo_apresentador":"",
          "url_foto_apresentador":"",
          "url_foto_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-07-26_10-33-22_221782_caa2a8c4.png",
          "url_foto_full_categoria":"",
          "url_foto_v_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-29-06_221782_ad0ccdcc.jpg",
          "videos":[
             "Array"
          ]
       },
       {
          "apresentacao_apresentador":"",
          "arquivos_categoria":[
             "Array"
          ],
          "cod_categoria":"561",
          "cod_categoria_pai":"0",
          "cod_cliente":"1258",
          "cor_primaria":"#970ff0",
          "descricao_categoria":"",
          "flg_mostrar_label":"1",
          "nome_apresentador":"",
          "nome_categoria":"Geografia",
          "ordem_categoria":"50",
          "subtitulo_apresentador":"",
          "url_foto_apresentador":"",
          "url_foto_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-07-26_11-05-43_221782_eaa5f79d.png",
          "url_foto_full_categoria":"",
          "url_foto_v_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-29-24_221782_6b4713bf.jpg",
          "videos":[
             "Array"
          ]
       },
       {
          "apresentacao_apresentador":"",
          "arquivos_categoria":[
             "Array"
          ],
          "cod_categoria":"564",
          "cod_categoria_pai":"0",
          "cod_cliente":"1258",
          "cor_primaria":"#1c43ff",
          "descricao_categoria":"",
          "flg_mostrar_label":"1",
          "nome_apresentador":"",
          "nome_categoria":"Ciências",
          "ordem_categoria":"100",
          "subtitulo_apresentador":"",
          "url_foto_apresentador":"",
          "url_foto_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-38-21_221782_ae24b2e6.png",
          "url_foto_full_categoria":"",
          "url_foto_v_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-37-34_221782_1dd69d7f.jpg",
          "videos":[
             "Array"
          ]
       },
       {
          "apresentacao_apresentador":"",
          "arquivos_categoria":[
             "Array"
          ],
          "cod_categoria":"565",
          "cod_categoria_pai":"0",
          "cod_cliente":"1258",
          "cor_primaria":"#105693",
          "descricao_categoria":"",
          "flg_mostrar_label":"1",
          "nome_apresentador":"",
          "nome_categoria":"Ensino Religioso",
          "ordem_categoria":"200",
          "subtitulo_apresentador":"",
          "url_foto_apresentador":"",
          "url_foto_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-45-04_221782_e59193b0.png",
          "url_foto_full_categoria":"2023-08-02_16-44-39_221782_8cf0bb44.jpg",
          "url_foto_v_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-43-48_221782_be697639.jpg",
          "videos":[
             "Array"
          ]
       },
       {
          "apresentacao_apresentador":"",
          "arquivos_categoria":[
             "Array"
          ],
          "cod_categoria":"566",
          "cod_categoria_pai":"0",
          "cod_cliente":"1258",
          "cor_primaria":"#360a84",
          "descricao_categoria":"",
          "flg_mostrar_label":"1",
          "nome_apresentador":"",
          "nome_categoria":"Arte",
          "ordem_categoria":"500",
          "subtitulo_apresentador":"",
          "url_foto_apresentador":"",
          "url_foto_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-52-09_221782_d3910c3c.png",
          "url_foto_full_categoria":"",
          "url_foto_v_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-52-10_221782_c5df1e28.jpg",
          "videos":[
             "Array"
          ]
       },
       {
          "apresentacao_apresentador":"",
          "arquivos_categoria":[
             "Array"
          ],
          "cod_categoria":"567",
          "cod_categoria_pai":"0",
          "cod_cliente":"1258",
          "cor_primaria":"#970ff0",
          "descricao_categoria":"",
          "flg_mostrar_label":"1",
          "nome_apresentador":"",
          "nome_categoria":"Educação Física",
          "ordem_categoria":"500",
          "subtitulo_apresentador":"",
          "url_foto_apresentador":"",
          "url_foto_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-53-42_221782_f6b0efee.png",
          "url_foto_full_categoria":"",
          "url_foto_v_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-53-43_221782_828d9569.jpg",
          "videos":[
             "Array"
          ]
       },
       {
          "apresentacao_apresentador":"",
          "arquivos_categoria":[
             "Array"
          ],
          "cod_categoria":"568",
          "cod_categoria_pai":"0",
          "cod_cliente":"1258",
          "cor_primaria":"#1c43ff",
          "descricao_categoria":"",
          "flg_mostrar_label":"1",
          "nome_apresentador":"",
          "nome_categoria":"Lingua inglesa",
          "ordem_categoria":"600",
          "subtitulo_apresentador":"",
          "url_foto_apresentador":"",
          "url_foto_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-55-12_221782_a6846648.png",
          "url_foto_full_categoria":"",
          "url_foto_v_categoria":"https://2.phsplay.com.br/storage/categorias/1258/2023-08-02_16-55-13_221782_000376ac.jpg",
          "videos":[
             "Array"
          ]
       }
    ],
    "destaques":[
       {
          "chamada_destaque":"",
          "cod_aovivo":"1000534",
          "cod_cliente":"1258",
          "cod_destaque":"329",
          "cod_video":"0",
          "custom_url":"",
          "departamentos_destaque":[
             "Array"
          ],
          "nome_destaque":"Destaque 1",
          "ordem_destaque":"20",
          "show_btn_destaque":"0",
          "status_destaque":"1",
          "target_blank":"0",
          "titulo_destaque":"",
          "url_banner":"",
          "url_banner_mobile":""
       }
    ]
 } as any;

